### ISSUE TITLE
How to get transaction id from simple pay

### ISSUE THREAD

**Issue by pmaingi** [paypal/adaptivepayments-sdk-java#11]
Hi There,
Is there a way to get transaction id when doing simple payments ?
I have passkey but am stuck on getting the transactin id.

Thanks

**Comment by juwlee** [comment]
@pmaingi Please see [PayPal developer docs](https://developer.paypal.com/webapps/developer/docs/classic/api/adaptive-payments/PaymentDetails_API_Operation/).

**Comment by pmaingi** [comment]
@juwlee Thank you
