### ISSUE TITLE
Incorrect Subtotal Chain (2 Recipients)

### ISSUE THREAD

**Issue by Gaudon** [paypal/adaptivepayments-sdk-java#13]
When performing a PayRequest with 2 recipients, the buyer's checkout screen only shows the total for the primary receiver. 

IE: If the total is $15 and the primary receiver is set to receive $14, while the secondary $1, the purchase page from the AP token will show $14 even though they get charged for $15. Why?

**Comment by ppmtscory** [comment]
Hmm.. that seems off.  Can you please let me know the paykey for that payment so that I can look to see how it was set up?

**Comment by Gaudon** [comment]
These are all sandbox payments but here's on I just did up:

AP-7UR5582567538880S

**Comment by Gaudon** [comment]
This should have been $10 (Primary) + $0.50 (Secondary).

**Comment by ppmtscory** [comment]
Did you complete the payment?  I'm unable to look up the payment with the paykey unless it completes.

**Comment by Gaudon** [comment]
I did not, I'll do it real quick, sorry.

**Comment by Gaudon** [comment]
Should be good now.

**Comment by Gaudon** [comment]
I think this might be fine actually. maybe I'm just using it wrong. 

IE: primary + secondary should not = total. 

The primary receivers amount should be the pay total, and the secondary is just deducted from it. 

I was manually doing the math and assuming the amount the buyer would see would be the combined total of all recipients rather than being the primary with all other amounts taken away from that.

**Comment by ppmtscory** [comment]
Thanks!  Looking at it, it's working as expected.  The amount on the checkout page is showing $10 CAD correctly.  When utilizing Chained Payments, whatever you want the total amount to be, needs to be set as the Primary total and the secondary just gets a cut of the Primary.  OR - exactly how you just explained it above...  :)

**Comment by Gaudon** [comment]
Yeap it's my mistake, my apologies it's been a very long night / day at this point. :)
