### ISSUE TITLE
Mobile Express Checkout style webUI with AP Token?

### ISSUE THREAD

**Issue by Gaudon** [paypal/adaptivepayments-sdk-java#14]
Presently I'm doing a chained payment on android but generating the payKey on the server and returning that to the client appended to the following URL:

PAYPAL_TEST_PAYMENT_URL = "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_ap-payment&paykey=";

Is there a version of this process that is more suited for mobile (This url is returned to the mobile client and opened externally) and similar to the express checkout which doesn't support chain payments (as far as I'm aware of).

**Comment by ppmtscory** [comment]
Unfortunately there is no mobile optimized payment flow for Adaptive Payments.  There's our [MPL](https://github.com/paypal/sdk-packages/tree/gh-pages/MPL) product for native Android apps, but if you went that route, please keep in mind that MPL is no longer being enhanced.

**Comment by Gaudon** [comment]
Yeah I actually did implement the MPL first but ran into a couple of issues. Primarily I don't believe the MPL supports guest checkout (required), where as the new SDK does (but doesn't support chain payments). Which left me back at square one, without a payment scheme that could fit the business model. 

This method I've opted for now could technically work if I leverage the IRN information and callback post paypal provides. While it isn't pretty (ie: non mobile checkout experience on mobile), I don't see another way around it unless I'm wrong about the MPL not supporting guest checkout.

**Comment by ppmtscory** [comment]
You are correct that MPL does not support guest checkout.

**Comment by kim1882** [comment]
Perhaps you're looking for "Embedded Payments"...in combination with Adaptive Payments?
![screenshot_2015-03-25-16-46-34](https://cloud.githubusercontent.com/assets/5282118/10008600/342de1ca-6096-11e5-837b-409c00c0df67.png)
Check this info: https://developer.paypal.com/docs/classic/adaptive-payments/ht_ap-embeddedPayment-curl-etc/

**Comment by Gaudon** [comment]
This was similar to what I was looking for Kim, but I couldn't figure out how (if possible) that it could function in a way similar to the current payment mechanism. IE: Providing the client that is nothing more than a URL and Pay Key that would launch a "slightly more" mobile user friendly experience in a browser on a mobile device. 

If there is a static link I can use in combination with a payKey I'd certainly be interested though.

**Comment by kim1882** [comment]
I tested with adaptive payments.
The example form needs a payKey, into the hidden field with name "paykey",
I generate the paykey by calling a service with the appropriate parameters,
my server returns a paykey and I set it into the field, when the user
clicks on the button "submit", the browser opens and asks the user to
authenticate to continue with the transaction.
The only difference is how is shown to the user, but the behaviour is the
same.

**Comment by Gaudon** [comment]
Ah ok.. so rather than returning a URL + PayKey that points directly to a paypal URL, you're instead redirecting them to your own hosted page (with embedded paykey) to support this form I take it?

**Comment by kim1882** [comment]
The example in the link I sent you, shows this:
<form action="
https://www.sandbox.paypal.com/webapps/adaptivepayment/flow/pay" target=
"PPDGFrame" class="standard">
The payKey you get, already contains all the information you need about
what needs to happen after the user pays (simple, parallel or chained
payment).
Yes, the form is hosted on my own server, but after the user clicks on
"submit" (i.e. "pay now") it's redirected to paypal.

**Comment by Gaudon** [comment]
Yeap makes sense, it's an interesting way to go about it that might provide a better experience than the default checkout experience (desktop like on mobile). I'll certainly take a look at it and see how it feels.

Thanks
