### ISSUE TITLE
Adaptive Chained Payment - Fee's Bug?

### ISSUE THREAD

**Issue by Gaudon** [paypal/adaptivepayments-sdk-java#15]
Just curious if this is working as intended.

Configuring a chained payment between 3 parties (A -> B -> DELAY -> C).

Configuration is such that C pays fees. ["SECONDARYONLY"]

Issuing a refund at step B (prior to funds making it to C, and effectively cancelling the primary -> secondary transaction) results in the full amount going back to A without ever incurring any fee's despite the A -> B transaction occurring.

Is this working as intended?

**Comment by pp-randy** [comment]
I would think A would be the primary and B and C would be secondary, so these 2 would get the fees.  How are you delaying the payment to just C? Did payment fail going to C then reverse?

**Comment by Gaudon** [comment]
A is the Sender, B is the primary recipient (Business) and C is the secondary recipient (individual). 

The fee's are configured such that C pays them. 

If it matters this was a sandbox test using PayPal balance. Perhaps that's why fee's weren't triggered?

I can re-test with a credit card, and will momentarily.

**Comment by pp-randy** [comment]
Oh... A is the sender got it!  

C would pay the fee if it made it to C.

**Comment by Gaudon** [comment]
Right, so in this case it doesn't make it to C because a refund is issued prior to the execute payment request. 

I was just wondering if it's normal that no fee's are incurred at any point in this transaction.

**Comment by Gaudon** [comment]
Also I just tested it with A using a credit card to pay instead of PayPal balance and the refund was still transaction fee free (that's a mouth full). 

Just wanted some reassurance that this is functioning as intended and there shouldn't be any fee's associated with a cancelled transaction configured in this way.

Thanks.

**Comment by kim1882** [comment]
Yes, that is correct. 
Even if you issue a refund after C paid the fees,
* In case of a full refund, PayPal will refund the full fee amount,
* In case of a partial refund, PayPal will refund a percentage of the fee,
as explained here: https://www.paypal.com/us/webapps/helpcenter/helphub/article/?solutionId=FAQ1672

**Comment by Gaudon** [comment]
Hey Kim, 

Thanks for that.. This is kind of what I was wondering about.. As far as I know, I can't do a partial refund for this type of transaction (The API tells me that's not permitted and returns with something similar to partial_refunds_are_not_permitted_for_this_type_of_transaction). 

With that being said, I see this on that page:

Fixed fees - $0.30 USD per transaction - are not refundable. To learn more about variable and fixed transaction fees, click Fees at the bottom of any PayPal page.

When I execute this transaction and refund combination, there is no $0.30 "non-refundable" fee associated with any of the transactions. 

Is that correct?

**Comment by kim1882** [comment]
I think the "fixed fee" would be charged when the payment was executed (C
got the funds), but if that didn't happen, no one would pay that fixed fee,
it's pretty much the same as if the 90-day period expired and you never
completed the payment, funds are returned to the buyer (A). I'm not 100%
sure about this.
You might have better luck asking the technical support team:
https://ppmts.custhelp.com/app/home

**Comment by Gaudon** [comment]
Understood, I'll assume since this library is so dated it's "working as intended" anyway heh. Thanks again.
