### ISSUE TITLE
how to get  "API Test Credentials"

### ISSUE THREAD

**Issue by XiaoxiaoJoker** [paypal/adaptivepayments-sdk-java#17]
sorry for my poor english.
https://developer.paypal.com/docs/classic/lifecycle/sb_credentials/;
```java
		// Sample Certificate credential
		 configMap.put("acct1.UserName", "certuser_biz_api1.paypal.com");
		 configMap.put("acct1.Password", "D6JNKKULHN3G5B8A");
		 configMap.put("acct1.CertKey", "password");
		 configMap.put("acct1.CertPath", "src/main/resources/sdk-cert.p12");
```
I created a Live Credentials follow this:https://developer.paypal.com/docs/classic/api/apiCredentials/;
but i don't know how to create a test Credentials like sample code above ,should i submit a app first?who can help me? thanks.
sorry for my poor engilsh again.

**Comment by pp-randy** [comment]
@XiaoxiaoJoker were you able to figure out what you needed?
