### ISSUE TITLE
Single Payout on sync_mode='true' always pending

### ISSUE THREAD

**Issue by av12** [paypal/adaptivepayments-sdk-java#23]
SDK/Library version: 
Environment: Is this issue in Sandbox 
Language, language version, and OS: Example: Java 1.8.0_101-b13 on Ubuntu 16.10 

hi  i am sending money to others i am using payout rest api. i am using single payout.in my requirement i need immediate response. so can tell me how can i do. and which api is better for this requirement.

*i sending request is:
-d '{"sender_batch_header":{"sender_batch_id":"0.6612174481338032",
    "email_subject":"You have a Payout!"},"items":[{"recipient_type":
      "Email","amount":{"currency":"USD","value":"5.2"},"note":
      "Thanks for Using HomeWorkPaper.com.Have a Great Day","receiver":
      "exaact.test-facilitator@gmail.com","sender_item_id":
      "0.6612174481338032"}]}
i sending responseis:
' com.paypal.base.rest.PayPalResource - response: {"batch_header":{"payout_batch_id":"A47HU2FKW9VZC","batch_status":"PENDING","sender_batch_header":{"sender_batch_id":"0.6612174481338032","email_subject":"You have a Payout!"}},"links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payouts/A47HU2FKW9VZC","rel":"self","method":"GET","encType":"application/json"}]}

**Comment by xiaoleih41** [comment]
Sync mode payout has been deprecated. Due to the bandwidth required for payout calls, we have to process asynchronously. All requests will be queued and be processed later.

**Comment by av12** [comment]
Ok.how can i get response whether transaction success  or not.how much time it will take to send

**Comment by av12** [comment]
hi.i am using asynchronous payout api. here i am creating batch.but in Batch i am sending only single item.(sending single receiver only). can you tell me how much time will take execute single item.
when i call three methods one by one i got  some times http delay and retry response . 
i am using sandbox enevironment
*i sending request is:	
batch = payout.create(apiContext, new HashMap<String, String>());
String payoutBatchId = batch.getBatchHeader().getPayoutBatchId();
PayoutBatch payoutbatch = Payout.get(apiContext, payoutBatchId);
if (payoutbatch != null) {
String payoutItemId = payoutbatch.getItems().get(0).getPayoutItemId();
PayoutItemDetails item = PayoutItem.get(apiContext, payoutItemId);

**Comment by av12** [comment]
Hi I am using payout api in sandbox environment. I am getting http read out time. I set read out time to 60sec. What this error. How to overcome this problem. Anyone suggest me.
I’m getting response is:

[2018-01-22]--[14:31:44.781] [http-nio-8080-exec-119] ERROR
com.paypal.base.HttpConnection - Caught exception while handling error response
java.net.SocketTimeoutException: Read timed out

**Comment by av12** [comment]
Hi anyone respond. I waiting for response

**Comment by pp-randy** [comment]
Can  you provide the updated request logging?  I see `exaact.test-facilitator@gmail.com` , can you confirm your sender and reciever are different accounts?

**Comment by pp-randy** [comment]
Also this is not a highly monitored repository since the Adaptive Payments platform is not longer supported for new integrations, I would encourage future issues to be filed here: https://github.com/paypal/PayPal-Java-SDK.

**Comment by pp-randy** [comment]
> Ok.how can i get response whether transaction success or not.how much time it will take to send

You should use a webhook to notify your system when the Payout Batch is completed.

**Comment by av12** [comment]
Yes sender ana reciever are different accounts. Sender has business account. I’m using sender credentials for api context

**Comment by av12** [comment]
thanks randy. finally i got response from you.

**Comment by pp-randy** [comment]
Do you have any open issues left I need to address @av12?

**Comment by av12** [comment]
I’m getting socket time out. In ten cases  three time I haveing this error. Error is 
2018-01-22]--[14:31:44.781] [http-nio-8080-exec-119] ERROR
com.paypal.base.HttpConnection - Caught exception while handling error response
java.net.SocketTimeoutException: Read timed out

**Comment by av12** [comment]
I’m getting socket time out. In ten cases  three time I haveing this error. I changed my sdk what you have suggested with but problem haven’t resolved  Error is 
2018-01-22]--[14:31:44.781] [http-nio-8080-exec-119] ERROR
com.paypal.base.HttpConnection - Caught exception while handling error response
java.net.SocketTimeoutException: Read timed out

**Comment by pp-randy** [comment]
I'm having trouble reproducing the random timeouts.  

You can confirm you are using asynchronous now?  Can you provide the request JSON so I can see if it helps me reproduce.

**Comment by xiaoleih41** [comment]
Payout API is the only API that PayPal has for payout. You may consider to use a different product than PayPal to do payout.
